name: Terraform Apply
on:
  workflow_dispatch:
jobs:
  terraform:
    name: Deploy with Terraform
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.5.7
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Debug environment
        run: |
          echo "Current directory: $(pwd)"
          echo "PATH: $PATH"
          terraform --version
          echo "Directory contents:"
          ls -la
          
      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          # Set up AWS credentials directly instead of using the action
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
          echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
          echo "region = $AWS_REGION" >> ~/.aws/credentials
          
      - name: Check if terraform directory exists
        run: |
          if [ -d "terraform" ]; then
            echo "Terraform directory exists"
            ls -la terraform/
          else
            echo "Terraform directory does not exist"
            echo "Repository contents:"
            ls -la
          fi
          
      - name: Terraform Init
        run: |
          cd terraform || (echo "Creating terraform directory" && mkdir -p terraform && cd terraform)
          terraform init
        
      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan
        
      - name: Terraform Apply
        env:
          TF_VAR_ami_id: ${{ secrets.AMI_ID }}
        run: |
          cd terraform
          terraform apply -auto-approve
