name: Terraform cd

on:
  workflow_dispatch:

jobs:
  setup-terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: false

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7  

      - name: Verify Terraform installation
        run: terraform -version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform 

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -var "ami_id=${{ secrets.AMI_ID }}"
        
      - name: Terraform Apply
        env:
          TF_VAR_ami_id: ${{ secrets.AMI_ID }}
          TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: terraform
        run: terraform apply -var "ami_id=${{ secrets.AMI_ID }}" --auto-approve
