name: Terraform Apply
on:
  workflow_dispatch:
jobs:
  terraform:
    name: Deploy with Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Debug environment
        run: |
          echo "Current directory: $(pwd)"
          echo "PATH: $PATH"
          echo "Directory contents:"
          ls -la
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Install Terraform manually
        run: |
          sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install -y terraform=1.5.7
          terraform --version
          
      - name: Check if terraform directory exists
        run: |
          if [ -d "terraform" ]; then
            echo "Terraform directory exists"
            ls -la terraform/
          else
            echo "Terraform directory does not exist"
            echo "Repository contents:"
            ls -la
          fi
          
      - name: Terraform Init
        run: |
          cd terraform || (echo "Creating terraform directory" && mkdir -p terraform && cd terraform)
          terraform init
        
      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan
        
      - name: Terraform Apply
        env:
          TF_VAR_ami_id: ${{ secrets.AMI_ID }}
        run: |
          cd terraform
          terraform apply -auto-approve
