name: Terraform Setup Test

on:
  workflow_dispatch:  # Trigger manually

jobs:
  setup-terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7  

      - name: Verify Terraform installation
        run: terraform -version

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform  
